# Generated by Django 3.2.13 on 2023-04-30 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendee',
            name='email',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
